# Generated by Django 3.2.2 on 2021-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
