# Generated by Django 3.2.2 on 2021-05-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210519_1824'),
        ('website', '0008_auto_20210519_2031'),
    ]

    operations = [
    ]
