# Generated by Django 3.2.2 on 2021-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210515_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benifits',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effect',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uses',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
