# Generated by Django 3.2.2 on 2021-05-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210520_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='default',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.product'),
        ),
    ]
