# Generated by Django 3.2.2 on 2021-05-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210523_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('customer', 'use_default')},
        ),
    ]
