# Generated by Django 3.2.2 on 2021-05-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_shippingaddress_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together=set(),
        ),
    ]
