# Generated by Django 3.2.2 on 2021-05-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_shippingaddress_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='use_default',
        ),
    ]
